version: '3.6'
services:
  db:
    container_name: mysql-ct
    image: mysql:5
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: 'root'
    volumes:
      - mysql-volume:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin-ct
    image: phpmyadmin/phpmyadmin
    ports:
        - "8080:80"
    depends_on:
        - db
    environment:
      PMA_HOST: db

      
volumes:
  mysql-volume: