version: '3.7'
services:
  # web:
  #   container_name: python-ct
  #   build: .
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "8081:80"
  #   environment:
  #     DATABASE_URL: postgres://root@postgres/main
    
  postgres:
    restart: always
    container_name: postgres-ct
    image: postgres:9.6.2-alpine
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: main
    
  pgadmin:
    container_name: pgadmin-ct
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 8080:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - postgres:pgsql-server
      
volumes:
  db-data:
  pgadmin-data: