version: '3.6'
services:
  db:
    container_name: mysql-ct
    image: mysql:5
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: 'root'
    ports:
      - "8081:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./mysql/init/.:/docker-entrypoint-initdb.d/.:ro

  phpmyadmin:
    container_name: phpmyadmin-ct
    image: phpmyadmin/phpmyadmin
    ports:
        - "8080:80"
    depends_on:
        - db
    environment:
      PMA_HOST: db
      
volumes:
  mysql-volume:
