version: '3.3'
services:
    web:
        container_name: python-ct
        build:.
        command: gunicorn -b 0.0.0.0:8000 todosapp.wsgi:application
        depends_on:
          - postgres
        volumes:
          - .:/src
        ports:
          - "8000:8000"
        environment:
          DATABASE_URL: postgres://root-pg@postgres/main
      
    postgres:
        restart: always
        container_name: postgres-ct
        image: postgres:9.6.2-alpine
        volumes:
        - /postgres:/docker-entrypoint-initdb.d
        - db-data:/var/lib/postgresql/data
        environment:
          POSTGRES_USER: root-pg
          POSTGRES_PASSWORD: root-pg
          POSTGRES_DB: main
      
    pgadmin:
        image: dpage/pgadmin4:4.18
        restart: always
        environment:
        PGADMIN_DEFAULT_EMAIL: root@root.com
        PGADMIN_DEFAULT_PASSWORD: root
        PGADMIN_LISTEN_PORT: 80
        ports:
            - "8080:80"
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        links:
            - "db:pgsql-server"
        
    volumes:
        db-data:
        gadmin-data: